name: ci
on: [push]
jobs:
  test:
    uses: bahmutov/cypress-workflows/.github/workflows/parallel.yml@v1
    with:
      n: 4
      group: 'All tests'
    secrets:
      recordKey: ${{ secrets.CYPRESS_RECORD_KEY }}