name: End to End Tests - Prod

on:
  # Runs every Tuesday and Thursday at 2pm IST
  schedule:
    - cron:  '30 8 * * 2,4'

jobs:
  end-to-end-test-prod:
    runs-on: macos-latest
    environment: End to End Test - Production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.18
      - name: Install dependencies
        run: npm install --prefix cypress
      - name: Prepare for end to end tests
        run: npm run setup:env
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
          browser: chrome
          tag: ${{ secrets.E2E_TESTS_ENV }}
      - name: 'Upload screenshots and videos to Slack'
        uses: trymbill/cypress-slack-video-upload-action@v1.3.0
        if: failure()
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channels: 'integration_github_events'
          message-text: ':pepe-dance: End to End tests End to End tests for Partner Dashboard (on prod) just got completed. I have placed the screenshots and videos in this thread :pepe-dance:'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      E2E_TESTS_REFRESH_TOKEN: ${{ secrets.E2E_TESTS_REFRESH_TOKEN }}
      E2E_TESTS_ORG_ID: ${{ secrets.E2E_TESTS_ORG_ID }}
      APP_URL: ${{ secrets.APP_URL }}